export { default as LoginPage } from './Login'
export { default as RegisterPage } from './Register'
export { default as ForgetPasswordPage } from './Forget'
export { default as VerifyPage } from './Verify'
export { default as ResetPasswordPage } from './Reset'
export { default as HomePage } from './Home'
export { default as CoursesPage } from './Courses'
export { default as CourseDetailPage } from './CourseDetail'
